services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - infra-test-net
    restart: unless-stopped
  
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    hostname: orchestrator
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__RabbitMq: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    networks:
      - infra-test-net
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      seaweedfs:
        condition: service_healthy
      
    restart: unless-stopped

  hypervisor:
    build:
      context: ./hypervisor/hypervisor
      dockerfile: Dockerfile
    container_name: hypervisor
    hostname: hypervisor
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    group_add:
      - ${DOCKER_GID:?Please set the this env in .env file}
    networks:
      - infra-test-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    hostname: seaweedfs
    networks:
      - infra-test-net
    volumes:
      - seaweedfs_data:/data
    command: >
      server -s3
      -s3.port=8333
      -ip.bind=0.0.0.0
      -dir=/data
      -master.volumeSizeLimitMB=1024
      -master.max=1
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O http://127.0.0.1:9333/cluster/status || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/18/docker
      POSTGRES_DB: aura-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=pl-PL --encoding=UTF8"
      TZ: Europe/Warsaw
    stop_grace_period: 45s
    shm_size: 256mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data_test:/var/lib/postgresql
    networks:
      - infra-test-net
    restart: unless-stopped

  nginx-infra-reverse-proxy:
    build:
      context: ./nginx-infra-reverse-proxy/reverse-proxy
      dockerfile: Dockerfile
    container_name: nginx-infra-reverse-proxy
    hostname: nginx-infra-reverse-proxy
    networks:
      - infra-test-net
    volumes:
      - ./nginx-infra-reverse-proxy/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  example-web-server:
    build:
      context: ./example-web-server/ExampleWebServer
      dockerfile: Dockerfile
    container_name: example-web-server
    hostname: example-web-server
    networks:
      - infra-test-net
    restart: unless-stopped

networks:
  infra-test-net:
    name: infra-test-net
    driver: bridge
    ipam:
      config:
          - subnet: 172.16.0.0/16
            gateway: 172.16.0.1

volumes:
  seaweedfs_data: